apiVersion: v1
kind: Secret
metadata:
  name: pguser-credentials
  namespace: database
  labels:
    app: pgsql
type: Opaque
data:
  password: cGd1c2VyQGRiMTIz          # Corrected: pguser@db123 (No newline)
  user: cGd1c2Vy                        # Corrected: pguser (This one was already correct)
