apiVersion: v1
kind: Pod
metadata:
  name: hostapp
  namespace: default
  labels:
    app: host
spec:
  containers:
  - name: hostapp
    image: ubuntu:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
    command:
      - sleep
      - "3600"
    ports:
    - containerPort:  80
    volumeMounts:
    - name: hostapp-volMnt
      mountPath: /opt
  volumes:
    - name: hostapp-vol
      hostPath:
        path: /mnt/host-data
        type: DirectoryOrCreate