apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment-app
  namespace: database
  labels:
      app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "700m"
          limits:
            memory: "700Mi"
            cpu: "900m"
        ports:
        - containerPort: 27017
          name: mongodb-port
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: root_user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: root_password