apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: database
  labels:
    app: mongo
type: Opaque
data:
  root_password: bW9uZ29wYXNzd29yZEAxMjM=      # Corrected: mongopassword@123 (No newline)
  root_user: bW9uZ291c2Vy                    # Corrected: mongouser (This one was already correct)
