apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: database
  labels:
      app: phpmyadmin-pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-pgsql
  template:
    metadata:
      labels:
        app: phpmyadmin-pgsql
    spec:
      containers:
      - name: phpmyadmin-pgsql-container
        image: phpmyadmin:latest
        resources:
          requests:
            memory: "400Mi"
            cpu: "500m"
          limits:
            memory: "600Mi"
            cpu: "700m"
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: pgsql-svc.database.svc.cluster.local
        - name: PMA_PORT
          value: "5432"