apiVersion: v1
kind: Secret
metadata:
  name:  pgadmin-credentials
  namespace: database
type: Opaque
data:
  email: YWRtaW5AcGdhZG1pbi5vcmc=  #This is base64 encoded value of admin@pgadmin.org
  password: YWRtaW5AMTIzNA==       #This is base64 encoded value of admin1234