apiVersion: v1
kind: Service
metadata:
  name: pgadmin-pgsql-svc
  namespace: database
spec:
  selector:
    app: pgadmin-pgsql
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80

---

# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: database
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: pgadmin.jenishchhowala.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin-pgsql-svc
            port:
              number: 80