apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
  namespace: database
labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:8.0
        resources:
          requests:
            memory: "500Mi"
            cpu: "700m"
          limits:
            memory: "700Mi"
            cpu: "900m"
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: initial-root-password
                key: password
          - name: MYSQL_DATABASE
            value: userdb 
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: user-credentials
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-credentials
                key: password