apiVersion: v1
kind: Secret
metadata:
  name: initial-root-password
  namespace: database
labels:
    app: mysql
type: Opaque
data:
  password: YWRtaW5AamVuaXNoLTEyMwo= #the decrypted password is admin@jenish-123

---

apiVersion: v1
kind: Secret
metadata:
  name: user-credentials
  namespace: database
labels:
    app: mysql
type: Opaque
data:
  password: dXNlcmRiQDEyMwo= #the decrypted password is userdb@123
  user: dXNlcmRi #the decrypted username is userdb

