apiVersion: v1
kind: Secret
metadata:
  name: initial-root-password
  namespace: database
  labels:
    app: mysql
type: Opaque
data:
  password: YWRtaW5AamVuaXNoLTEyMw==  # Corrected: admin@jenish-123 (No newline)

---

apiVersion: v1
kind: Secret
metadata:
  name: user-credentials
  namespace: database
  labels:
    app: mysql
type: Opaque
data:
  password: dXNlcmRiQDEyMw==          # Corrected: userdb@123 (No newline)
  user: dXNlcmRi                      # Corrected: userdb (This one was already correct)
